### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by whatever193** [vanhbakaa/moonbix-bot#1]
2024-09-21 21:32:12 | INFO     | 221 - d | Logged in
Traceback (most recent call last):
  File "C:\Users\accli\Downloads\Compressed\New folder\moonbix-bot-main\moonbix-bot-main\bot\core\tapper.py", line 386, in run
    self.get_user_info(session)
  File "C:\Users\accli\Downloads\Compressed\New folder\moonbix-bot-main\moonbix-bot-main\bot\core\tapper.py", line 222, in get_user_info
    logger.info(f"{self.session_name} | Total point: <yellow>{data__['metaInfo']['totalGrade']}</yellow> | <white>Risk Passed: <red>{data__['riskPassed']}</red> | Qualified: <red>{data__['qualified']}</red></white>")
TypeError: 'NoneType' object is not subscriptable
2024-09-21 21:32:12 | ERROR    | 409 - d | Unknown error: 'NoneType' object is not subscriptable

**Comment by vanhbakaa** [comment]
that's a new account?

**Comment by whatever193** [comment]
> that's a new account?

yes, it not working with new account?

**Comment by vanhbakaa** [comment]
> > that's a new account?
> 
> yes, it not working with new account?

okay got it i forgot about that. im going to fix it now

**Comment by vanhbakaa** [comment]
fixed
