### ISSUE TITLE
Unknown error while trying to get game data: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by sametbaglar** [vanhbakaa/moonbix-bot#12]
2024-09-23 14:51:56 | INFO     | 456 - samet | start after 4s
2024-09-23 14:52:03 | SUCCESS  | 208 - samet | Get access token sucessfully
2024-09-23 14:52:03 | INFO     | 269 - samet | Logged in
2024-09-23 14:52:03 | INFO     | 270 - samet | Total point: 12650 | Risk Passed: True | Qualified: True
2024-09-23 14:52:04 | INFO     | 354 - samet | Starting to play game...
2024-09-23 14:52:04 | INFO     | 356 - samet | Attempts left: 6
2024-09-23 14:52:04 | SUCCESS  | 364 - samet | Game 7eaba13aab754700f3ed0c19b9b573a3 started successful
2024-09-23 14:52:04 | INFO     | 368 - samet | Wait 45.04889296037665s to complete the game...
2024-09-23 14:52:50 | ERROR    | 226 - samet | Unknown error while trying to get game data: Expecting value: line 1 column 1 (char 0)
2024-09-23 14:52:50 | INFO     | 381 - samet | Sleep 6.668215609300199s...

**Comment by vanhbakaa** [comment]
fixed

**Comment by sametbaglar** [comment]
2024-09-23 16:04:18 | INFO     | 530 - samet | Attempts left: 1
2024-09-23 16:04:19 | SUCCESS  | 539 - samet | Game b4452e6c8077e7e26ee2950dc5617a68 started successful
2024-09-23 16:04:19 | INFO     | 544 - samet | Wait 45.031624920547216s to complete the game...
2024-09-23 16:05:04 | INFO     | 320 - samet | Playing game!
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/moonbix-bot/bot/core/tapper.py", line 329, in get_game_data
    reward_d = choice(list(obj_type['trap'].keys()))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/random.py", line 373, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence
2024-09-23 16:05:04 | ERROR    | 386 - samet | Unknown error while trying to get game data: Cannot choose from an empty sequence
2024-09-23 16:05:04 | INFO     | 557 - samet | Sleep 7.740614378128613s...
2024-09-23 16:05:12 | INFO     | 530 - samet | Attempts left: 1
2024-09-23 16:05:12 | WARNING  | 552 - samet | Failed to start game, msg: {'code': '116002', 'message': 'attempts not enough, user: 983847774, resource code: moon-bix.', 'messageDetail': None, 'data': None, 'success': False}
2024-09-23 16:05:12 | INFO     | 619 - samet | Sleep 2973s...
