### ISSUE TITLE
Failed to complete game issue

### ISSUE THREAD

**Issue by PTPL-LKO** [vanhbakaa/moonbix-bot#23]
error log:

```
2024-09-24 11:48:36 | INFO     | 343 - 3_AirZ | Playing game!
Traceback (most recent call last):
  File "D:\Safi\Work\MoonB\moonbix-bot\bot\core\tapper.py", line 427, in get_game_data   
    pos_y=sorted_pos_y[Total_tap])
          ~~~~~~~~~~~~^^^^^^^^^^^
IndexError: list index out of range
2024-09-24 11:48:36 | ERROR    | 445 - 3_AirZ | Unknown error while trying to get game data: list index out of range
2024-09-24 11:48:36 | INFO     | 618 - 3_AirZ | Sleep 9.715070462306933s...
2024-09-24 11:48:36 | SUCCESS  | 217 - shri | Get access token sucessfully
2024-09-24 11:48:36 | INFO     | 495 - shri | Logged in
2024-09-24 11:48:36 | INFO     | 496 - shri | Total point: 2900 | Risk Passed: True | Qualified: True
2024-09-24 11:48:37 | SUCCESS  | 669 - shri | Successfully completed task LOGIN | Reward:
 100
2024-09-24 11:48:38 | INFO     | 587 - 1_Jio | Starting to play game...
2024-09-24 11:48:38 | INFO     | 589 - 1_Jio | Attempts left: 6
2024-09-24 11:48:38 | SUCCESS  | 599 - 1_Jio | Game b569b200434e832897cb257ad4ca7ddc started successful
2024-09-24 11:48:38 | INFO     | 343 - 1_Jio | Playing game!
2024-09-24 11:48:38 | INFO     | 607 - 1_Jio | Wait 45.003797276684026s to complete the game...
2024-09-24 11:48:39 | INFO     | 587 - 2_JioZ | Starting to play game...
2024-09-24 11:48:39 | INFO     | 589 - 2_JioZ | Attempts left: 5
2024-09-24 11:48:40 | SUCCESS  | 599 - 2_JioZ | Game b569b200434e832897cb257ad4ca7ddc started successful
2024-09-24 11:48:40 | INFO     | 343 - 2_JioZ | Playing game!
2024-09-24 11:48:40 | INFO     | 607 - 2_JioZ | Wait 45.030717006669235s to complete the game...
2024-09-24 11:48:41 | INFO     | 587 - shri | Starting to play game...
2024-09-24 11:48:41 | INFO     | 589 - shri | Attempts left: 4
2024-09-24 11:48:43 | SUCCESS  | 599 - shri | Game b569b200434e832897cb257ad4ca7ddc started successful
2024-09-24 11:48:43 | INFO     | 343 - shri | Playing game!
2024-09-24 11:48:43 | INFO     | 607 - shri | Wait 45.02588546345256s to complete the game...
2024-09-24 11:48:45 | INFO     | 589 - 3_AirZ | Attempts left: 4
2024-09-24 11:48:46 | SUCCESS  | 599 - 3_AirZ | Game b569b200434e832897cb257ad4ca7ddc started successful
2024-09-24 11:48:46 | INFO     | 343 - 3_AirZ | Playing game!
2024-09-24 11:48:46 | INFO     | 607 - 3_AirZ | Wait 45.00823560696761s to complete the game...
2024-09-24 11:49:09 | WARNING  | 575 - Shri2 | Failed to complete game | 100: 1727158707339|177.597|213.290|-0.027|0|0|2|39|194;1727158710256|186.436|229.566|0.217|152.497|381.997|1|70|179;1727158713740|208.426|207.172|-0.398|314.112|450.865|1|70|118 Send this to me so i can fix it !
2024-09-24 11:49:09 | INFO     | 618 - Shri2 | Sleep 6.925988141477944s...
2024-09-24 11:49:15 | WARNING  | 575 - 5_hanz | Failed to complete game | 100: 1727158713840|217.222|221.660|-0.913|281.975|250.506|1|50|163;1727158716922|78.562|227.975|-0.899|258.528|315.826|1|70|78;1727158720698|222.160|221.905|-0.493|312.779|381.900|1|50|102 Send this to me so i can fix it !
2024-09-24 11:49:15 | INFO     | 618 - 5_hanz | Sleep 7.354444069160989s...
2024-09-24 11:49:16 | INFO     | 589 - Shri2 | Attempts left: 5
2024-09-24 11:49:17 | SUCCESS  | 599 - Shri2 | Game a6132d5fdf8cf6d70ae4023adef7028a started successful
2024-09-24 11:49:17 | INFO     | 343 - Shri2 | Playing game!
2024-09-24 11:49:17 | INFO     | 607 - Shri2 | Wait 45.04184845827221s to complete the game...
2024-09-24 11:49:20 | WARNING  | 575 - ShriBro | Failed to complete game | 75: 1727158718625|200.948|226.034|-0.166|217.466|324.288|1|70|180;1727158721836|159.531|217.976|0.179|130.115|379.710|1|50|195 Send this to me so i can fix it !
2024-09-24 11:49:20 | INFO     | 618 - ShriBro | Sleep 9.455385526948069s...
2024-09-24 11:49:22 | INFO     | 589 - 5_hanz | Attempts left: 5
2024-09-24 11:49:23 | SUCCESS  | 599 - 5_hanz | Game a6132d5fdf8cf6d70ae4023adef7028a started successful
2024-09-24 11:49:23 | INFO     | 343 - 5_hanz | Playing game!
2024-09-24 11:49:23 | INFO     | 607 - 5_hanz | Wait 45.015127688862265s to complete the game...
2024-09-24 11:49:24 | SUCCESS  | 572 - 1_Jio | Sucessfully earned: 0 from game !
2024-09-24 11:49:24 | INFO     | 618 - 1_Jio | Sleep 6.759868670528526s...
2024-09-24 11:49:25 | WARNING  | 575 - 2_JioZ | Failed to complete game | 165: 1727158724022|111.464|203.294|-0.926|240.185|255.639|2|60|120;1727158726707|111.081|223.980|-0.851|292.910|336.078|1|70|40;1727158730676|176.176|212.369|0.307|124.844|371.730|0|30|95;1727158734189|116.778|201.641|-0.812|374.995|387.308|0|50|63;1727158737281|172.775|210.426|0.706|0|0|1|16|164;1727158739830|211.614|212.782|-0.354|303.713|456.379|1|30|152;1727158742507|167.241|212.899|0.699|0|0|0|24|82;1727158745128|199.009|201.729|-0.378|317.303|491.157|1|70|103;1727158748273|143.106|203.240|0.213|0|0|0|75|81;1727158751771|223.056|203.887|-0.125|262.867|519.097|0|30|100;1727158754825|139.568|224.244|-0.511|313.218|516.232|1|50|59;1727158757353|178.811|221.054|-0.056|195.472|519.153|1|30|106 Send this to me so i can fix it !
2024-09-24 11:49:25 | INFO     | 618 - 2_JioZ | Sleep 5.387502620268672s...
2024-09-24 11:49:28 | WARNING  | 575 - shri | Failed to complete game | 190: 1727158726692|100.588|207.759|-0.826|251.405|310.683|0|50|171;1727158730185|145.137|212.848|-0.281|189.773|365.168|1|70|10;1727158733075|144.925|200.875|-0.166|174.337|375.588|2|60|90;1727158736970|87.353|228.720|-0.876|361.875|379.601|1|30|101;1727158740845|170.945|200.457|0.893|0|0|0|26|196;1727158744155|135.958|205.294|0.578|0|0|0|25|25;1727158746941|144.663|219.318|-0.740|384.247|437.292|0|30|70;1727158750629|189.375|214.707|0.319|115.914|433.311|1|50|134;1727158753331|165.633|202.999|0.002|165.170|432.303|1|50|159;1727158756449|215.699|202.930|-0.462|373.530|505.526|1|70|42;1727158759888|156.664|219.628|-0.010|159.928|530.819|1|30|19 Send this to me so i can fix it !
2024-09-24 11:49:28 | INFO     | 618 - shri | Sleep 6.560353740358169s...
2024-09-24 11:49:29 | INFO     | 589 - ShriBro | Attempts left: 5
2024-09-24 11:49:30 | WARNING  | 613 - ShriBro | Failed to start game, msg: {'code': '116002', 'message': 'attempts not enough, user: 6667553236, resource code: moon-bix.', 'messageDetail': None, 'data': None, 'success': False}
2024-09-24 11:49:30 | INFO     | 680 - ShriBro | Sleep 2970s...
2024-09-24 11:49:30 | INFO     | 589 - 1_Jio | Attempts left: 5
2024-09-24 11:49:31 | WARNING  | 613 - 1_Jio | Failed to start game, msg: {'code': '116002', 'message': 'attempts not enough, user: 6667553236, resource code: moon-bix.', 'messageDetail': None, 'data': None, 'success': False}
2024-09-24 11:49:31 | INFO     | 680 - 1_Jio | Sleep 2533s...
2024-09-24 11:49:31 | INFO     | 589 - 2_JioZ | Attempts left: 4
2024-09-24 11:49:32 | WARNING  | 613 - 2_JioZ | Failed to start game, msg: {'code': '116002', 'message': 'attempts not enough, user: 6667553236, resource code: moon-bix.', 'messageDetail': None, 'data': None, 'success': False}
2024-09-24 11:49:32 | INFO     | 680 - 2_JioZ | Sleep 3248s...
2024-09-24 11:49:32 | WARNING  | 575 - 3_AirZ | Failed to complete game | 0: 1727158729423|76.639|205.814|-0.649|131.527|270.081|0|30|192 Send this to me so i can fix it !       
2024-09-24 11:50:02 | WARNING  | 575 - Shri2 | Failed to complete game | 175: 1727158760328|170.413|213.796|-0.974|335.076|252.072|1|50|197;1727158763640|104.908|227.371|-0.952|356.969|308.408|1|50|189;1727158766891|207.635|211.414|-0.640|304.131|327.312|1|50|32;1727158770402|123.383|210.312|-0.840|344.541|353.194|2|60|90;1727158773774|79.655|212.216|-0.567|176.484|352.833|1|30|8;1727158776490|162.273|212.528|0.226|121.931|386.280|1|70|9;1727158779682|129.536|210.867|0.079|112.723|421.850|1|30|170;1727158782841|75.642|223.183|-0.693|0|0|0|41|66;1727158786587|113.152|216.486|-0.161|151.930|454.262|1|30|147;1727158789249|106.975|220.517|-0.031|115.413|495.724|0|30|123 Send this to me so i can fix it !
2024-09-24 11:50:02 | INFO     | 618 - Shri2 | Sleep 6.004992855439548s...
2024-09-24 11:50:08 | WARNING  | 575 - 5_hanz | Failed to complete game | 0: 1727158766090|114.815|226.779|-0.986|322.262|262.302|0|30|84 Send this to me so i can fix it !
2024-09-24 11:50:08 | INFO     | 618 - 5_hanz | Sleep 6.8744070441694305s...
2024-09-24 11:50:08 | INFO     | 589 - Shri2 | Attempts left: 1
2024-09-24 11:50:09 | WARNING  | 613 - Shri2 | Failed to start game, msg: {'code': '116002', 'message': 'attempts not enough, user: 6667553236, resource code: moon-bix.', 'messageDetail': None, 'data': None, 'success': False} 
2024-09-24 11:50:09 | INFO     | 680 - Shri2 | Sleep 2944s...
2024-09-24 11:50:15 | INFO     | 680 - 5_hanz | Sleep 2603s...
```

**Comment by cookie027** [comment]
I also have this problem, and I have two other problems

# Failed to start game
Failed to start game, msg: {'code': '116002', 'message': 'attempts not enough, user: , resource code: moon-bix.', 'messageDetail': None, 'data': None, 'success': False}

# TypeError
 | SUCCESS  | 599 -  | Game  started successful
 | INFO     | 343 -  | Playing game!
Traceback (most recent call last):
  File "moonbix-bot/bot/core/tapper.py", line 433, in get_game_data
    data_pl = ';'.join(game_data_payload)
TypeError: sequence item 13: expected str instance, NoneType found
 | ERROR    | 445 -  | Unknown error while trying to get game data: sequence item 13: expected str instance, NoneType found

**Comment by vanhbakaa** [comment]
i fixed now. Also dont use too many accounts with same ip

**Comment by prognt** [comment]
just updated, 1acc = 1 ip
```
moonbix: 2024-09-24 20:18:18 | WARNING  | 572 - 2613 | Failed to complete game | 115: 1727191054855|142.994|207.710|-0.623|270.232|367.542|1|70|145;1727191058663|139.129|203.884|-0.491|265.573|428.254|2|60|120;1727191065281|189.785|209.397|-0.296|270.250|468.761|0|50|123;1727191068129|112.594|205.669|-0.558|299.796|484.383|1|50|78 Send this to me so i can fix it !
moonbix: 2024-09-24 20:18:20 | WARNING  | 572 - 9461 | Failed to complete game | 40: 1727191058301|142.051|218.061|-0.824|252.277|293.724|2|60|120;1727191061656|193.797|215.262|-0.652|314.772|355.822|0|50|36 Send this to me so i can fix it !
moonbix: 2024-09-24 20:18:12 | WARNING  | 572 - 7264 | Failed to complete game | 10: 1727191049787|215.341|217.697|-0.325|233.100|269.387|1|30|93 Send this to me so i can fix it !
moonbix: 2024-09-24 20:18:10 | WARNING  | 572 - 4145 | Failed to complete game | 85: 1727191048660|130.955|204.825|-0.965|318.186|255.844|2|60|90;1727191051442|203.243|213.151|-0.022|205.870|334.595|0|50|195;1727191057374|122.994|217.273|-0.594|233.648|367.027|0|30|153;1727191060787|164.001|218.510|-0.183|195.643|388.313|0|30|30;1727191066989|99.312|213.874|-0.649|277.397|422.490|1|50|18;1727191075968|218.473|222.474|-0.341|302.024|453.161|1|30|179;1727191078564|188.016|215.784|-0.555|362.111|476.648|1|70|194 Send this to me so i can fix it !
```

**Comment by vanhbakaa** [comment]
> just updated, 1acc = 1 ip
> 
> ```
> moonbix: 2024-09-24 20:18:18 | WARNING  | 572 - 2613 | Failed to complete game | 115: 1727191054855|142.994|207.710|-0.623|270.232|367.542|1|70|145;1727191058663|139.129|203.884|-0.491|265.573|428.254|2|60|120;1727191065281|189.785|209.397|-0.296|270.250|468.761|0|50|123;1727191068129|112.594|205.669|-0.558|299.796|484.383|1|50|78 Send this to me so i can fix it !
> moonbix: 2024-09-24 20:18:20 | WARNING  | 572 - 9461 | Failed to complete game | 40: 1727191058301|142.051|218.061|-0.824|252.277|293.724|2|60|120;1727191061656|193.797|215.262|-0.652|314.772|355.822|0|50|36 Send this to me so i can fix it !
> moonbix: 2024-09-24 20:18:12 | WARNING  | 572 - 7264 | Failed to complete game | 10: 1727191049787|215.341|217.697|-0.325|233.100|269.387|1|30|93 Send this to me so i can fix it !
> moonbix: 2024-09-24 20:18:10 | WARNING  | 572 - 4145 | Failed to complete game | 85: 1727191048660|130.955|204.825|-0.965|318.186|255.844|2|60|90;1727191051442|203.243|213.151|-0.022|205.870|334.595|0|50|195;1727191057374|122.994|217.273|-0.594|233.648|367.027|0|30|153;1727191060787|164.001|218.510|-0.183|195.643|388.313|0|30|30;1727191066989|99.312|213.874|-0.649|277.397|422.490|1|50|18;1727191075968|218.473|222.474|-0.341|302.024|453.161|1|30|179;1727191078564|188.016|215.784|-0.555|362.111|476.648|1|70|194 Send this to me so i can fix it !
> ```

try to run with 1 account only and tell me if u still ger that error

**Comment by prognt** [comment]
1 account ok
```
moonbix: 2024-09-24 20:32:16 | INFO     | 24 - Your version is up to date!
moonbix: 2024-09-24 20:32:16 | INFO     | 100 - Detected 1 sessions | 1 proxies
moonbix: 2024-09-24 20:32:16 | INFO     | 692 - 4145 | start after 7s
moonbix: 2024-09-24 20:32:26 | INFO     | 201 - 4145 | Proxy IP: ***.***.19.224
moonbix: 2024-09-24 20:32:26 | INFO     | 635 - 4145 | bind with proxy ip: socks5://SsSMkv:WeKf41@***.***.19.224:9439
moonbix: 2024-09-24 20:32:32 | SUCCESS  | 217 - 4145 | Get access token sucessfully
moonbix: 2024-09-24 20:32:33 | INFO     | 492 - 4145 | Logged in
moonbix: 2024-09-24 20:32:33 | INFO     | 493 - 4145 | Total point: 2800 | Risk Passed: True | Qualified: True
moonbix: 2024-09-24 20:32:33 | INFO     | 584 - 4145 | Starting to play game...
moonbix: 2024-09-24 20:32:33 | INFO     | 586 - 4145 | Attempts left: 6
moonbix: 2024-09-24 20:32:34 | SUCCESS  | 596 - 4145 | Game 17daea3e22e7cd7688c02a1f04e352c3 started successful
moonbix: 2024-09-24 20:32:34 | INFO     | 343 - 4145 | Playing game!
moonbix: 2024-09-24 20:32:34 | INFO     | 604 - 4145 | Wait 45.01840241987311s to complete the game...
moonbix: 2024-09-24 20:33:20 | SUCCESS  | 569 - 4145 | Sucessfully earned: 140 from game !
moonbix: 2024-09-24 20:33:20 | INFO     | 615 - 4145 | Sleep 9.109222905525199s...
```

**Comment by vanhbakaa** [comment]
> 1 account ok
> 
> ```
> moonbix: 2024-09-24 20:32:16 | INFO     | 24 - Your version is up to date!
> moonbix: 2024-09-24 20:32:16 | INFO     | 100 - Detected 1 sessions | 1 proxies
> moonbix: 2024-09-24 20:32:16 | INFO     | 692 - 4145 | start after 7s
> moonbix: 2024-09-24 20:32:26 | INFO     | 201 - 4145 | Proxy IP: ***.***.19.224
> moonbix: 2024-09-24 20:32:26 | INFO     | 635 - 4145 | bind with proxy ip: socks5://SsSMkv:WeKf41@***.***.19.224:9439
> moonbix: 2024-09-24 20:32:32 | SUCCESS  | 217 - 4145 | Get access token sucessfully
> moonbix: 2024-09-24 20:32:33 | INFO     | 492 - 4145 | Logged in
> moonbix: 2024-09-24 20:32:33 | INFO     | 493 - 4145 | Total point: 2800 | Risk Passed: True | Qualified: True
> moonbix: 2024-09-24 20:32:33 | INFO     | 584 - 4145 | Starting to play game...
> moonbix: 2024-09-24 20:32:33 | INFO     | 586 - 4145 | Attempts left: 6
> moonbix: 2024-09-24 20:32:34 | SUCCESS  | 596 - 4145 | Game 17daea3e22e7cd7688c02a1f04e352c3 started successful
> moonbix: 2024-09-24 20:32:34 | INFO     | 343 - 4145 | Playing game!
> moonbix: 2024-09-24 20:32:34 | INFO     | 604 - 4145 | Wait 45.01840241987311s to complete the game...
> moonbix: 2024-09-24 20:33:20 | SUCCESS  | 569 - 4145 | Sucessfully earned: 140 from game !
> moonbix: 2024-09-24 20:33:20 | INFO     | 615 - 4145 | Sleep 9.109222905525199s...
> ```

wait it maybe have some problem with your proxy mine still fine.
i will upload a version which u can run many accounts without proxy for you

**Comment by vanhbakaa** [comment]
fixed use newest version
