### ISSUE TITLE
Unknow error

### ISSUE THREAD

**Issue by whiitees** [vanhbakaa/moonbix-bot#24]
2024-09-24 13:36:51 | INFO     | 589 - Moonbix | Attempts left: 6
2024-09-24 13:36:52 | SUCCESS  | 599 - Moonbix | Game d3228dfa190d956098dedca57e23db93 started successful
2024-09-24 13:36:52 | INFO     | 343 - Moonbix | Playing game!
Traceback (most recent call last):
  File "D:\BOT\moonbix-bot-main\moonbix-bot-main\bot\core\tapper.py", line 433, in get_game_data
    data_pl = ';'.join(game_data_payload)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 10: expected str instance, NoneType found
2024-09-24 13:36:52 | ERROR    | 445 - Moonbix | Unknown error while trying to get game data: sequence item 10: expected str instance, NoneType found

Than it start playing the new game and earn points

**Comment by whiitees** [comment]
When It play last game and than go sleep I got this error:
2024-09-24 13:41:23 | INFO     | 680 - Moonbix | Sleep 2619s...
2024-09-24 14:25:03 | WARNING  | 500 - Moonbix | Get user data failed: {'code': '100002002', 'message': 'Request failed. Please check if you are logged in.', 'messageDetail': {'title': None, 'type': None, 'icon': None, 'action': None, 'linkTitle': None, 'linkUrl': None}, 'data': None, 'success': False}
2024-09-24 14:25:04 | WARNING  | 539 - Moonbix | Get tasks list failed: {'code': '100002002', 'message': 'Request failed. Please check if you are logged in.', 'messageDetail': {'title': None, 'type': None, 'icon': None, 'action': None, 'linkTitle': None, 'linkUrl': None}, 'data': None, 'success': False}
Traceback (most recent call last):
  File "D:\BOT\moonbix-bot-main\moonbix-bot-main\bot\core\tapper.py", line 666, in run
    for task in task_list:
TypeError: 'NoneType' object is not iterable
2024-09-24 14:25:04 | ERROR    | 688 - Moonbix | Unknown error: 'NoneType' object is not iterable

**Comment by vanhbakaa** [comment]
fixed

**Comment by vanhbakaa** [comment]
please dont open the app in telegram while you are running bot
