### ISSUE TITLE
bot error

### ISSUE THREAD

**Issue by iamspa** [vanhbakaa/moonbix-bot#35]
get error like this
Traceback (most recent call last):
  File "D:\AirDrop\moonbix-bot\bot\core\tapper.py", line 674, in run
    await self.play_game(session)
  File "D:\AirDrop\moonbix-bot\bot\core\tapper.py", line 597, in play_game
    f"{self.session_name} | <green>Game <cyan>{data_['data']['gameTag']}</cyan> started successful</green>")
                                               ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'gameTag'
2024-10-02 14:42:33 | ERROR    | 687 - Amirin | Unknown error: 'gameTag'

**Comment by vanhbakaa** [comment]
the project currently paused
