### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by H4X0RA** [vanhbakaa/moonbix-bot#38]
please help, i got this error after last update

Activating virtual environment...
Dependencies already installed, skipping installation.
Skipping .env copying
Starting the bot...
Traceback (most recent call last):
  File "C:\Users\h4x0ra\Desktop\MoonbixBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\h4x0ra\Desktop\MoonbixBot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\h4x0ra\Desktop\MoonbixBot-main\bot\utils\launcher.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
done
PLEASE EDIT .ENV FILE
Press any key to continue . . .

**Comment by H4X0RA** [comment]
i already tried pip install requests, not helped

**Comment by vanhbakaa** [comment]
What is your python version

**Comment by vanhbakaa** [comment]
> i already tried pip install requests, not helped

Wait i will fix next update

**Comment by EugeneZviR** [comment]
Traceback (most recent call last):
  File "W:\moonbix-bot-main\bot\core\tapper.py", line 788, in run
    await self.play_game(session)
  File "W:\moonbix-bot-main\bot\core\tapper.py", line 606, in play_game
    sessionId = data_['data']['sessionId']
KeyError: 'sessionId'
2024-10-04 15:12:18 | ERROR    | 801 - nomo | Unknown error: 'sessionId'

What problem can be?

**Comment by kerimaksoy** [comment]
i got the same Unknown error: 'sessionId'

**Comment by iamspa** [comment]
got error like this

{'code': '000000', 'message': None, 'messageDetail': None, 'data': {'gameTag': 'a353cd51723e26400ae53c3d5e925f26', 'specialRewardId': None, 'cryptoMinerConfig': {'gameDuration': None, 'hookSwipeSpeed': 300, 'finalHookSwipeSpeed': 500, 'itemSettingList': [{'type': 'BONUS', 'speed': 80, 'size': 60, 'quantity': 1, 'rewardValueList': [30]}, {'type': 'TRAP', 'speed': 100, 'size': 50, 'quantity': 1, 'rewardValueList': [-20]}, {'type': 'REWARD', 'speed': 150, 'size': 50, 'quantity': 3, 'rewardValueList': [25, 25, 25]}, {'type': 'REWARD', 'speed': 200, 'size': 30, 'quantity': 5, 'rewardValueList': [10, 10, 10, 10, 10]}, {'type': 'REWARD', 'speed': 100, 'size': 70, 'quantity': 2, 'rewardValueList': [50, 50]}, {'type': 'TRAP', 'speed': 150, 'size': 30, 'quantity': 2, 'rewardValueList': [-10, -10]}]}}, 'success': True}
Traceback (most recent call last):
  File "C:\Users\Administrator\moonbix-bot\bot\core\tapper.py", line 788, in run
    await self.play_game(session)
  File "C:\Users\Administrator\moonbix-bot\bot\core\tapper.py", line 606, in play_game
    sessionId = data_['data']['sessionId']
                ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'sessionId'

**Comment by RootXecution** [comment]
did you fix the captcha issue?
