### ISSUE TITLE
error

### ISSUE THREAD

**Issue by meliqa92** [vanhbakaa/moonbix-bot#49]
today i receive this error

Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.
                 It can be downloaded at https://aka.ms/vs/16/release/vc_redist.x64.exe
Traceback (most recent call last):
  File "C:\Users\p_melikidze\Desktop\moonbix-bot-main\bot\core\tapper.py", line 800, in run
    await self.play_game(session)
  File "C:\Users\p_melikidze\Desktop\moonbix-bot-main\bot\core\tapper.py", line 678, in play_game
    from bot.core.solver.captcha_solver import solve_captcha
  File "captcha_solver.pyx", line 4, in init bot.core.solver.captcha_solver
  File "payload.pyx", line 6, in init payload
  File "classifier.pyx", line 1, in init classify.classifier
  File "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\transformers\dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\transformers\utils\__init__.py", line 27, in <module>
    from .chat_template_utils import DocstringParsingException, TypeHintParsingException, get_json_schema
  File "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\transformers\utils\chat_template_utils.py", line 39, in <module>
    from torch import Tensor
  File "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\torch\lib\c10.dll" or one of its dependencies.
2024-10-06 11:27:48 | ERROR    | 813 - Moonbix | Unknown error: [WinError 126] The specified module could not be found. Error loading "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\torch\lib\c10.dll" or one of its dependencies.

**Comment by vanhbakaa** [comment]
dowload https://aka.ms/vs/16/release/vc_redist.x64.exe as it said then reinstall torch library

**Comment by meliqa92** [comment]
I installed it, but now it can't open the captcha with me. does it work with you

**Comment by vanhbakaa** [comment]
What did it say ?

**Comment by meliqa92** [comment]
i use vps i think not working correctly vps
