### ISSUE TITLE
ModuleNotFoundError: No module named 'aiocfscrape'

### ISSUE THREAD

**Issue by AadilGillani** [vanhbakaa/moonbix-bot#50]
Activating virtual environment...
Dependencies already installed, skipping installation.
Skipping .env copying
Starting the bot...
Traceback (most recent call last):
  File "C:\Users\aadil\Downloads\moonbix-bot-main\moonbix-bot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\aadil\Downloads\moonbix-bot-main\moonbix-bot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\aadil\Downloads\moonbix-bot-main\moonbix-bot-main\bot\utils\launcher.py", line 13, in <module>
    from bot.core.tapper import run_tapper_no_thread
  File "C:\Users\aadil\Downloads\moonbix-bot-main\moonbix-bot-main\bot\core\tapper.py", line 14, in <module>
    from aiocfscrape import CloudflareScraper
ModuleNotFoundError: No module named 'aiocfscrape'
done
PLEASE EDIT .ENV FILE
Press any key to continue . . .

This is comming even after doing multiples things even reinstalling python

**Comment by Mr-Mk7** [comment]
i am having the same problem with many of the bot

**Comment by Tiny-Stark** [comment]
Have you tried manually install it?
1. run 'cmd' on your bot folder (C:\Users\aadil\Downloads\moonbix-bot-main\moonbix-bot-main)
2. run 'pip install aiocfscrape'
