### ISSUE TITLE
Gametag error

### ISSUE THREAD

**Issue by meliqa92** [vanhbakaa/moonbix-bot#57]
2024-10-07 12:18:49 | SUCCESS  | 228 - Moonbix | Get access token sucessfully
2024-10-07 12:18:50 | INFO     | 502 - Moonbix | Logged in
2024-10-07 12:18:50 | INFO     | 503 - Moonbix | Total point: 149085 | Risk Passed: True | Qualified: False
2024-10-07 12:18:50 | INFO     | 595 - Moonbix | Starting to play game...
2024-10-07 12:18:50 | INFO     | 598 - Moonbix | Attempts left: 5
2024-10-07 12:18:51 | INFO     | 646 - Moonbix | Attempt to solve captcha (default)...
Traceback (most recent call last):
  File "captcha_solver.pyx", line 14, in bot.core.solver.captcha_solver.solve_captcha
  File "payload.pyx", line 42, in build_payload
  File "classifier.pyx", line 19, in classify
  File "classifier.pyx", line 44, in get_instance
  File "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\transformers\modeling_utils.py", line 3886, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\transformers\models\clip\modeling_clip.py", line 1151, in __init__
    text_model = CLIPTextModel._from_config(text_config, attn_implementation=config._attn_implementation)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\transformers\modeling_utils.py", line 1519, in _from_config
    model = cls(config, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\transformers\models\clip\modeling_clip.py", line 957, in __init__
    self.text_model = CLIPTextTransformer(config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\transformers\models\clip\modeling_clip.py", line 852, in __init__
    self.encoder = CLIPEncoder(config)
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\transformers\models\clip\modeling_clip.py", line 761, in __init__
    self.layers = nn.ModuleList([CLIPEncoderLayer(config) for _ in range(config.num_hidden_layers)])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\transformers\models\clip\modeling_clip.py", line 761, in <listcomp>
    self.layers = nn.ModuleList([CLIPEncoderLayer(config) for _ in range(config.num_hidden_layers)])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\transformers\models\clip\modeling_clip.py", line 534, in __init__
    self.self_attn = CLIP_ATTENTION_CLASSES[config._attn_implementation](config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\transformers\models\clip\modeling_clip.py", line 261, in __init__
    self.k_proj = nn.Linear(self.embed_dim, self.embed_dim)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p_melikidze\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\linear.py", line 99, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: [enforce fail at alloc_cpu.cpp:114] data. DefaultCPUAllocator: not enough memory: you tried to allocate 1048576 bytes.
Traceback (most recent call last):
  File "C:\Users\p_melikidze\Desktop\moonbix-bot-main\bot\core\tapper.py", line 800, in run
    await self.play_game(session)
  File "C:\Users\p_melikidze\Desktop\moonbix-bot-main\bot\core\tapper.py", line 721, in play_game
    f"{self.session_name} | <green>Game <cyan>{data_['data']['gameTag']}</cyan> started successful</green>")
                                               ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'gameTag'
2024-10-07 12:19:00 | ERROR    | 813 - Moonbix | Unknown error: 'gameTag'
2024-10-07 12:20:15 | INFO     | 502 - Moonbix | Logged in
2024-10-07 12:20:15 | INFO     | 503 - Moonbix | Total point: 149085 | Risk Passed: True | Qualified: False
2024-10-07 12:20:15 | INFO     | 595 - Moonbix | Starting to play game...
2024-10-07 12:20:15 | INFO     | 598 - Moonbix | Attempts left: 5
2024-10-07 12:20:16 | INFO     | 646 - Moonbix | Attempt to solve captcha (default)...
done
PLEASE EDIT .ENV FILE
Press any key to continue . . .

**Comment by meliqa92** [comment]
I think captcha not working correctly

**Comment by vanhbakaa** [comment]
the bot not support that captcha type
