### ISSUE TITLE
Captcha Error

### ISSUE THREAD

**Issue by mujahidkhanofficial** [vanhbakaa/moonbix-bot#71]
2024-10-21 22:55:43 | INFO     | 530 - Account-0 | Starting to play game...
2024-10-21 22:55:43 | INFO     | 533 - Account-0 | Attempts left: 6
2024-10-21 22:55:45 | INFO     | 581 - Account-0 | Attempt to solve captcha (ship)...
Traceback (most recent call last):
  File "C:\Users\Mujjo\Desktop\New folder\moonbix-bot\bot\core\query.py", line 735, in run
    await self.play_game(session)
  File "C:\Users\Mujjo\Desktop\New folder\moonbix-bot\bot\core\query.py", line 613, in play_game
    from bot.core.solver.captcha_solver import solve_captcha
ModuleNotFoundError: No module named 'bot.core.solver.captcha_solver'
2024-10-21 22:55:45 | ERROR    | 748 - Account-0 | Unknown error: No module named 'bot.core.solver.captcha_solver'

**Comment by vanhbakaa** [comment]
USE PYTHON 3.11.5 BRO PLEASE READ BEFORE USE
